apps/clients/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps.clients import views

app_name = "clients_show"

urlpatterns = [
    path("", login_required(views.ShowAllClientsView.as_view()), name="show_all"),
    path("create", login_required(views.ClientCreateView.as_view()), name="create"),
    path(
        "<int:pk>/",
        include(
            [
                path("edit", login_required(views.ClientUpdateView.as_view()), name="edit"),
            ]
        ),
    ),
    path("about_us", login_required(views.AboutUsView.as_view()), name="about_us"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.base.urls")),
    path("clients/", include("apps.clients.urls")),
    path("client_validation/", include("apps.clients_validation.urls")),
    path("blogs/", include("apps.blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico"))),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/clients/views/about_us_view.py
from django.views.generic import ListView

from apps.clients.models import Client


class AboutUsView(ListView):
    model = Client
    template_name = "clients_show/about_us.html"
    context_object_name = "clients"

apps/templates/clients_show/about_us.html
{% extends '_helpers/_base.html' %}
{% load static %}

{% block body %}
    <div class="about-section" style="font-size: 1.2em">
        <h1>About Us</h1>
        <p>We are a company of market enthusiasts who strive to improve our market understanding.</p>
        <p><span style="font-size: 1.3em;"><i><u>Our goal</u> </i></span>is to help people to get a better and more accurate understanding of market bias via our strategy! </p>
    </div>

    <h2 style="text-align:center">Our Team</h2>
    <div class="row-about-us">
        <div class="column">
            <div class="card">
                <img src="{% static '/img/vasya_avatar.jpg' %}" alt="Vasya" style="width:auto">
                <div class="container" style="color: black; width: auto;">
                    <h2>Vasyl Gutnik</h2>
                    <p class="title">CEO & Founder</p>
                    <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                    <p>vasyabest@cock.com</p>
                    <p>
                        <button class="button">Contact</button>
                    </p>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="{% static '/img/bohdan_avatar.jpg' %}" alt="Bohdan" style="width:auto">
                <div class="container" style="color: black; width: auto">
                    <h2>Bohdan Zavalii</h2>
                    <p class="title">Art Director</p>
                    <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                    <p>bohdan@cock.com</p>
                    <p>
                        <button class="button">Contact</button>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/clients_show/show_all.html
{% extends '_helpers/_base.html' %}

{% block body %}
    <h2>All clients admin area</h2>
    <a href="{% url 'clients_show:create' %}">
        <button type="button" class="btn btn-primary">Add a client</button>
    </a>
    <ol>
        {% for client in clients %}
            <li style="margin: .2em;">

                <span>{{ client.client_name }} - {{ client.is_live_account }} - {{ client.account_number }}</span>

                <a href="{% url 'clients_show:edit' pk=client.pk %}">
                    <button type="button" class="btn btn-secondary">Edit
                    </button>
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}