apps/base/urls.py
from django.urls import path

from apps.base.views import HomeView

urlpatterns = [path("", HomeView.as_view(), name="index")]

apps/clients_validation/urls.py
from django.urls import path

from apps.clients_validation import views

app_name = "clients"

urlpatterns = [
    path("", views.SignUpView.as_view(), name="signup"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.base.urls")),
    path("clients/", include("apps.clients.urls")),
    path("client_validation/", include("apps.clients_validation.urls")),
    path("blogs/", include("apps.blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico"))),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/base/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "index.html"

apps/templates/_helpers/_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Liquidus</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/49dbf474af.js" crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <link href="{% static "styles/index.css" %}" rel="stylesheet">
    <link href="{% static "styles/about_us.css" %}" rel="stylesheet">
</head>
<body id="bg"
      style="background-image: url('{% static "img/background_image.jpg" %}')">
{% include '_helpers/_header.html' %}
<div class="container-fluid">
    {% block body %}
        <p>I'm glad you are here!</p>
    {% endblock %}
</div>
</body>
</html>

apps/templates/_helpers/_header.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" id="headerLogo" href="{% url 'index' %}">
            <img src="{% static '/img/black_logo-removebg-preview.png' %}" alt="Logo" width="100" height="90"
                 id="headerText">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="color: white;">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        MORE
                    </a>
                    <ul class="dropdown-menu" id="moreDropdown">
                        <li><a class="dropdown-item" href="/clients/about_us">ABOUT</a></li>
                        <li><a class="dropdown-item" href="#">CONTACT</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <div class="dropdown_icons">
                            <li><a class="dropdown-item" href="https://www.youtube.com/channel/UC5deCaNgfUgQJ2tgvIE_bKA"
                                   target="_blank"><img src="{% static '/icons/youtube.svg' %}" alt="YT" width="20"
                                                        height="auto"></a></li>
                            <li><a class="dropdown-item" href="https://twitter.com/zavbog_LQ"
                                   target="_blank"><img src="{% static '/icons/twitter.svg' %}" alt="TW" width="20"
                                                        height="auto"></a></li>
                            <li><a class="dropdown-item" href="https://t.me/liqu_id_us"
                                   target="_blank"><img src="{% static '/icons/telegram.svg' %}" alt="TG" width="20"
                                                        height="auto"></a></li>
                        </div>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        PRODUCTS
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/blogs/">Daily Blog</a></li>
                        <li><a class="dropdown-item" href="#">Weekly Updates</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#"><i>LIQUIDUS University</i></a></li>
                    </ul>
                </li>
            </ul>
            <div class="d-flex justify-content-center align-items-center"
                 id="userGreetingDiv">
                {% if user.is_authenticated %}
{#                    <div id="clientGreeting">Hi, <i>{{ user.username }}!</i></div>#}
                    <div id="clientGreeting">ACCOUNT</div>
                    <div>
                        <a href="{% url 'logout' %}" id="clientGreeting">LOGOUT</a></div>
                {% else %}
                    <div id="login-clientGreeting-sign-up">
                        <a href="{% url 'login' %}" id="loginOrSignup"><i>LOG IN</i></a>
                        <span style="color: grey"> or </span>
                        <a href="{% url 'clients:signup' %}" id="loginOrSignup"><i>SIGN UP</i></a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>