apps/blog/urls.py
from django.contrib.auth.decorators import login_required

from . import views
from django.urls import path, include

from .views import AddBlogView, PostDetailView
from .categories_views.add_category import AddCategoryView
from apps.blog.categories_views.category_veiw import category_view

app_name = "blogs"

urlpatterns = [
    path("", views.PostList.as_view(), name="show_all"),
    path("<slug:slug>/", login_required(PostDetailView.as_view()), name="post_detail"),
    path("create", login_required(AddBlogView.as_view()), name="add_blog"),
    path("create_category", login_required(AddCategoryView.as_view()), name="add_category"),
    path("category/<str:cats>/", login_required(category_view), name="category"),
    path(
        "<int:pk>/",
        include(
            [
                path("edit", login_required(views.UpdateBlogView.as_view()), name="edit"),
                path("delete", login_required(views.DeleteBlogView.as_view()), name="delete"),
            ]
        ),
    ),
    path("like/<int:pk>", views.like_view, name="like_post"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.base.urls")),
    path("clients/", include("apps.clients.urls")),
    path("client_validation/", include("apps.clients_validation.urls")),
    path("blogs/", include("apps.blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico"))),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/blog/models.py
from django.db import models
from django.urls import reverse
from apps.clients_validation.models import AbstractClient
from ckeditor.fields import RichTextField

STATUS = ((0, "Draft"), (1, "Publish"))


class PostCategory(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("index")

    __repr__ = __str__


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(AbstractClient, on_delete=models.CASCADE, related_name="blog_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = RichTextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    snippet = models.CharField(max_length=220)

    # If default=1, then all posts will be immediately displayed on the page,
    # but if default=0, then admin should go to admin panel and approve it manually.
    status = models.IntegerField(choices=STATUS, default=1)
    blog_category = models.CharField(max_length=200, default="uncategorized")

    likes = models.ManyToManyField(AbstractClient, related_name="blog_post_likes")

    def total_likes(self):
        return self.likes.count()

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

apps/blog/forms.py
from .models import Comment, Post, PostCategory
from django import forms

# name cals two times in values_list() to get correct feedback from database
CATEGORY_CHOICES = PostCategory.objects.all().values_list("name", "name")
CATEGORY_CHOICES_LIST = list(CATEGORY_CHOICES)


class BlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "slug", "author", "blog_category", "content", "snippet")
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "slug": forms.TextInput(attrs={"class": "form-control"}),
            "author": forms.Select(attrs={"class": "form-control"}),
            "blog_category": forms.Select(choices=CATEGORY_CHOICES_LIST, attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
            "snippet": forms.Textarea(attrs={"class": "form-control"}),
        }


class EditBlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "slug", "blog_category", "content", "snippet")
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "slug": forms.TextInput(attrs={"class": "form-control"}),
            "blog_category": forms.Select(choices=CATEGORY_CHOICES_LIST, attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
            "snippet": forms.Textarea(attrs={"class": "form-control"}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "body": forms.Textarea(attrs={"class": "form-control", "placeholder": "Enter your comment here"}),
        }

apps/blog/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView

from .models import Post, PostCategory
from .forms import CommentForm, BlogForm, EditBlogForm
from django.shortcuts import render, get_object_or_404


def like_view(request, pk):
    post = get_object_or_404(Post, id=request.POST.get("post_id"))
    liked = False  # flake8: noqa: F841

    # If the user who clicked on 👍 already exists, then we remove him
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False  # flake8: noqa: F841
    else:
        # else we add/assign a like to the exact user
        post.likes.add(request.user)
        liked = True  # flake8: noqa: F841

    return HttpResponseRedirect(reverse("blogs:post_detail", args=[str(post.slug)]))


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "blogs/show_blogs.html"
    paginate_by = 3
    cats = PostCategory.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        cat_menu = PostCategory.objects.all()
        context = super().get_context_data(object_list=None, **kwargs)
        context["cat_menu"] = cat_menu
        return context


class AddBlogView(CreateView):
    model = Post
    form_class = BlogForm
    template_name = "blogs/add_post.html"
    success_url = reverse_lazy("blogs:show_all")


class UpdateBlogView(UpdateView):
    model = Post
    template_name = "blogs/update_post.html"
    form_class = EditBlogForm
    success_url = reverse_lazy("blogs:show_all")


class DeleteBlogView(DeleteView):
    model = Post
    template_name = "blogs/delete_post.html"
    success_url = reverse_lazy("blogs:show_all")


class PostDetailView(DetailView):
    model = Post
    template_name = "blogs/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs["slug"]

        # Comment form context data
        comment_form = CommentForm()
        post = get_object_or_404(Post, slug=slug)
        comments = post.comments.filter(active=True)

        # Likes context data
        blog_id = get_object_or_404(Post, slug=slug)
        total_likes = blog_id.total_likes()

        liked = bool(blog_id.likes.filter(id=self.request.user.id).exists())

        context["post"] = post
        context["comments"] = comments
        context["comment_form"] = comment_form
        context["total_likes"] = total_likes
        context["liked"] = liked
        return context

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(data=request.POST)
        self.object = self.get_object()
        slug = self.kwargs["slug"]
        post = get_object_or_404(Post, slug=slug)
        comments = post.comments.filter(active=True)
        new_comment = None

        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
        else:
            comment_form = CommentForm()
        return render(
            request,
            self.template_name,
            {"post": post, "comments": comments, "new_comment": new_comment, "comment_form": comment_form},
        )

apps/templates/blogs/add_category.html
{% extends '_helpers/_base.html' %}

{% block body %}
    <h2>Add Category</h2>
    <div class="add_blog_form-parent">
        <div class="form-group">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success" style="float: right;">Add category</button>
            </form>
        </div>
    </div>
{% endblock %}

apps/templates/blogs/add_post.html
{% extends '_helpers/_base.html' %}

{% block body %}
    <h2>Add Blog post</h2>
    <div class="add_blog_form-parent">
        <div class="form-group">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success" style="float: right;">Create</button>
            </form>
        </div>
    </div>
{% endblock %}

apps/templates/blogs/categories.html
{% extends '_helpers/_base.html' %}

{% block body %}
    {% if  category_posts %}

        <h2 style="text-align: center"><b><i>{{ cats }}</i></b> category</h2>
        <h4 style="text-align: center">{{ category_posts.count }} post{{ category_posts.count|pluralize }}</h4>
        {% for post in category_posts %}
            <div class="card mb-4">
                <div class="card-body">
                    {% if user.id == post.author.id or user.id == 1 %}
                        <a href="{% url 'blogs:edit' pk=post.pk %}">
                            <button type="button" class="btn btn-light" id="editBlogBtn">Edit blog 📝</button>
                        </a>
                        <a href="{% url 'blogs:delete' pk=post.pk %}">
                            <button class="btn-close" aria-label="Close"></button>
                        </a>
                    {% endif %}
                    <h2 class="card-title" style="color: darkolivegreen;">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }} </p>
                    <p class="card-text" style="color: black">{{ post.snippet }}</p>

                    <a href="{% url 'blogs:post_detail' post.slug %}" class="btn btn-primary">Read More
                        &rarr;</a>
                    <p class="comments-count">
                        {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
                    </p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h2 style="text-align: center;">Sorry, this page does not exist 😥 </h2>
    {% endif %}


    {% if is_paginated %}
        <nav aria-label="Page navigation conatiner"></nav>
        <ul class="pagination justify-content-center" id="paginator">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

apps/templates/blogs/delete_post.html
{% extends '_helpers/_base.html' %}

{% block body %}
    {% if user.id == post.author.id or user.id == 1 %}
        <div id="deleteConfirm">
            <h2>Delete Blog - <i><u>{{ post.title }}</u></i></h2>

            <p class="del-conf-text">Are you sure you want to delete this
                blog?</p>

            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Delete">
                <a href="{% url 'blogs:show_all' %}" class="btn btn-primary" style="color: white;">Back to the
                    blogs page</a>
            </form>
        </div>
    {% else %}
        <h2>You're not allowed to delete - {{ post.title }}. 😔</h2>
    {% endif %}
{% endblock %}

apps/templates/blogs/post_detail.html
{% extends '_helpers/_base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <a href="{% url 'blogs:show_all' %}" class="btn btn-primary" style="color: white;">&#8592 Back to the
        blogs page</a>
    <div class="container">
        <div class="row" id="detailBlogContainer">
            <div class="col-md-8 card mb-4  mt-3 left  top">
                <div class="card-body">
                    {% if user.id == post.author.id or user.id == 1 %}
                        <a href="{% url 'blogs:edit' pk=post.pk %}">
                            <button type="button" class="btn btn-light" id="editBlogBtn">Edit blog 📝</button>
                        </a>

                        <a href="{% url 'blogs:delete' pk=post.pk %}">
                            <button class="btn-close" aria-label="Close"></button>
                        </a>
                    {% endif %}
                    <h1 style="color: darkolivegreen;">{% block title %} {{ post.title }} {% endblock title %}</h1>
                    <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
                    <span class="card-text text-muted h6">Category: </span><a
                    href="{% url 'blogs:category' cats=post.blog_category|slugify %}" target="_blank"
                    class="card-text text-muted h6"><i>{{ post.blog_category }}</i></a>
                    <p></p>
                    <p class="card-text">{{ post.content | safe }}</p>
                    <br>
                    <!--  Adding likes to the post  -->
                    <form action="{% url 'blogs:like_post' pk=post.pk %}" method="post" style="float: right">
                        {% csrf_token %}
                        {% if liked %}
                            <button type="submit" name="post_id" value="{{ post.id }}"
                                    class="btn btn-outline-danger btn-sm">👎
                            </button>
                        {% else %}
                            <button type="submit" name="post_id" value="{{ post.id }}"
                                    class="btn btn-outline-info btn-sm">👍
                            </button>
                        {% endif %} - <span>{{ total_likes }} Like{{ total_likes|pluralize }}</span>
                    </form>
                    <!--  End of code  -->
                </div>
            </div>
            <!-- Comments section -->
            <div class="col-md-8 card mb-4  mt-3 ">
                <div class="card-body">
                    {% with comments.count as total_comments %}
                        <h3 class="comments-titles">
                            {{ total_comments }} comment{{ total_comments|pluralize }}
                        </h3>
                    {% endwith %}

                    {% for comment in comments %}
                        <div class="comments">
                            <p id="commentAuthor">
                                {{ comment.name }} |
                                <span class=" text-muted font-weight-normal" style="font-weight: normal">
                                    {{ comment.created_on }}
                                </span>
                            </p>
                            {{ comment.body | linebreaks }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- End of comments section -->
            <div class="col-md-8 card mb-4  mt-3 ">
                <div class="card-body">
                    {% if new_comment %}
                        <div class="alert alert-success" role="alert">
                            Your comment is awaiting moderation
                        </div>
                    {% else %}
                        <h3 class="comments-titles">Leave a comment</h3>
                        <form method="post" style="margin-top: 1.3em;">
                            {% csrf_token %}
                            {{ comment_form | crispy }}
                            <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/blogs/show_blogs.html
{% extends '_helpers/_base.html' %}

{% block body %}
    <h2 style="text-align: center;">Read our Latest blogs!</h2>

    <div class="container" id="blogsContainer">
        <div class="row">
            {% if user.is_authenticated %}
                <div class="add_buttons">
                    <!--  Add blog button  -->
                    {% if user.id == post.author.id or user.id == 1 %}
                        <a href="{% url 'blogs:add_blog' %}">
                            <button type="button" class="btn btn-success" id="addBlogBtn">➕ Add a blog</button>
                        </a>
                        <!--  Add category button  -->
                        <a href="{% url 'blogs:add_category' %}">
                            <button type="button" class="btn btn-primary" id="addBlogBtn">➕ Add a category</button>
                        </a>
                    {% endif %}
                </div>
            {% endif %}
            <div class="col-md-8 mt-3 left">
                {% for post in post_list %}
                    <div class="card mb-4">
                        <div class="card-body">
                            {% if user.id == post.author.id or user.id == 1 %}
                                <a href="{% url 'blogs:edit' pk=post.pk %}">
                                    <button type="button" class="btn btn-light" id="editBlogBtn">Edit blog 📝</button>
                                </a>

                                <a href="{% url 'blogs:delete' pk=post.pk %}">
                                    <button class="btn-close" aria-label="Close"></button>
                                </a>
                            {% endif %}
                            <!-- Blog Entries Column -->
                            <h2 class="card-title" style="color: darkolivegreen;">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }} </p>
                            <span class="card-text text-muted h6">Category: </span><a
                            href="{% url 'blogs:category' cats=post.blog_category|slugify %}" target="_blank"
                            class="card-text text-muted h6"><i>{{ post.blog_category }}</i></a>
                            <p></p>
                            <p class="card-text" style="color: black">{{ post.snippet }}</p>
{#                            <p class="card-text">{{ post.content|slice:":200"|safe }}...</p>#}
                            <a href="{% url 'blogs:post_detail' post.slug %}" class="btn btn-primary">Read More
                                &rarr;</a>
                            <p class="comments-count">
                                {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <!--  Category list  -->
            <div class="" id="categoriesList">
                <h3 style="color: white;padding-left: 10px">List of blog categories🔻</h3>
                <ul style="font-size: 1.1em;">
                    {% for category in cat_menu %}
                        <div>
                            <a
                                href="{% url 'blogs:category' cats=category|slugify %}" target="_blank"
                                class="category-item">▪
                                <i>{{ category }}</i></a>
                        </div>
                    {% endfor %}
                </ul>
            </div>
            <!--  End of category list  -->
        </div>
    </div>
    <!--  Page pagination  -->
    {% if is_paginated %}
        <nav aria-label="Page navigation conatiner"></nav>
        <ul class="pagination justify-content-center" id="paginator">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    {% endif %}
    <!--  End of page pagination  -->
{% endblock %}

apps/templates/blogs/update_post.html
{% extends '_helpers/_base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <h2>Edit your blog post</h2>
    <div class="add_blog_form-parent">
        <div class="form-group">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media}}
                {{ form | crispy}}
                <button type="submit" class="btn btn-success" style="float: right">Update</button>
            </form>

        </div>
    </div>
{% endblock %}